"0618 - Fix #618 - process lock implemented in server and documented here" (#619)
Co-authored-by: E Ciurana <pr3d4t0r@cime.net>

diff --git a/work/countyraid b/work/countyraid
--- a/work/countyraid
+++ b/work/countyraid
@@ -10,6 +10,7 @@ source "./vucommon.bash"
 source ./pyrunner
 
 export COUNTY_CASES_US_ENDPOINT="https://coronavirus-tracker-api.herokuapp.com/v2/locations?source=csbs"
+export CASES_OUTPUT="/tmp/countyraid.json"
 
 
 # *** main ***
@@ -19,7 +20,12 @@ echo "fetchcing counties data from $COUNTY_CASES_US_ENDPOINT"
 
 assertDatabaseOK
 
-curl -A "$PYAVKA_USER_AGENT" -s "$COUNTY_CASES_US_ENDPOINT" | jq -M '.locations' > "$COUNTY_CASES_CSBS_FILE" 
+curl -A "$PYAVKA_USER_AGENT" -s "$COUNTY_CASES_US_ENDPOINT" > "$CASES_OUTPUT"
+
+status="$?"
+[[ "$status" == "0" ]] || die "Unable to fetch counties data - error $status - output: $CASES_OUTPUT" 1
+
+cat "$CASES_OUTPUT" | jq -M '.locations' > "$COUNTY_CASES_CSBS_FILE" 
 
 python -m covidvu.pipeline.vucounty
 python -m covidvu.pipeline.vuhospitals
