0601 del pyavka2 (#610)
* "0601 - RC1 - Fix #601"

* "0601 - RC2 - Minor speed bump in world updates"

* "0601 - RC3 - Minor bug"

* "0601 - RC4 - Deaths reporting"

* "0601 - RC1 - Fix #601 - ready for roll out"

* "0601 - RC2 - Fix #601"

* "0601 - RC3 - Fix #601"

Co-authored-by: E Ciurana <pr3d4t0r@cime.net>

diff --git a/work/refreshdata b/work/refreshdata
--- a/work/refreshdata
+++ b/work/refreshdata
@@ -41,6 +41,12 @@ function assertSiteDataExists {
 } # assertSiteDataExists
 
 
+function assertJITDataToolsAvailable {
+    [[ -n $(which rustler) ]] || die "rustler tool not installed" 29
+    [[ -n $(which vtrustler) ]] || die "vtrustler Python module not installed" 30
+} # assertJITDataToolsAvailable
+
+
 function resetErrorNotification {
     echo "reset error notification file"
     [[ -e "$UPDATE_ERROR" ]] && rm -f "$UPDATE_ERROR"
@@ -82,7 +88,7 @@ function generateHospitalBedsData {
 
     printf "fetching current US hospital beds count\n  "
     cp -vf "$HOSPITAL_BEDS_US_FILE" "$hospitalBedsTargetFile"
-    [[ "0" != "$?" ]] && die "generateHospitalBedsData - failed" 18
+    [[ "0" != "$?" ]] && die "generateHospitalBedsData - failed; $HOSPITAL_BEDS_US_FILE -> $hospitalBedsTargetFile" 18
 } # generateHospitalBedsData
 
 
@@ -115,13 +121,16 @@ function generateJITData {
     #       ./refreshdata noop
     #
     #       ./refreshdata
-    echo "pyavka - grabbing the spreadsheet"
-    fetchJITDataSource
-    python3 -m covidvu.pipeline.pyavka
+#     echo "pyavka - grabbing the spreadsheet"
+#     fetchJITDataSource
+#     python3 -m covidvu.pipeline.pyavka
+
+    rustler
     ls -Alrt "$SITE_DATA_DIR"/*html
 
     echo "vuupdate - updating system with latest calculated updates"
-    python -m covidvu.pipeline.vuupdate confirmed deaths
+    python -m covidvu.pipeline.vuupdate
+    [[ "0" != "$?" ]] && die "vuupdate failed" 28
     ls -Alrt "$SITE_DATA_DIR"/*json  | awk '!/conf-int/ && !/mean-/'
 } # generateJITData
 
@@ -170,8 +179,9 @@ echo "*** COVIDvu - website refresh tool ***"
 assertSiteDataExists
 resetErrorNotification
 assertDatabaseOK
+assertJITDataToolsAvailable
 resetSiteData "$1"
-generateHospitalBedsData
+# generateHospitalBedsData
 generateUSCountiesData
 generateJITData
 packDataFiles
