"0525 - Confirmed JIT updates are working"

diff --git a/work/refreshdata b/work/refreshdata
--- a/work/refreshdata
+++ b/work/refreshdata
@@ -2,6 +2,7 @@
 
 # See: https://github.com/VirusTrack/COVIDvu/blob/master/LICENSE 
 # vim: set fileencoding=utf-8:
+# Version 2.0
 
 # crontab compliant :)
 
@@ -54,12 +55,6 @@ function resetErrorNotification {
 } # resetErrorNotification
 
 
-function assertCOVID19DirExists {
-    echo "assert $COVID_19_DIR directory exists"
-    [[ -d "./COVID-19" ]] || die "" 1 # nothing to do; silent fail
-} # assertCOVID19DirExists
-
-
 function assertCloudFrontConfig {
     [[ -n "$AWS_ACCESS_KEY_ID" ]] || die "AWS_ACCESS_KEY_ID is not set" 4
     [[ -n "$AWS_SECRET_ACCESS_KEY" ]] || die "AWS_SECRET_ACCESS_KEY is not set" 5
@@ -102,31 +97,6 @@ function nukeDeploymentSite {
 } # nukeDeploymentSite
 
 
-function updateCOVID19DataSources {
-    echo "refreshing COVID-19 JS CSSE dataset from GitHub" 
-
-    pushd "$COVID_19_DIR"
-    git checkout master
-    git fetch
-    git pull
-    [[ "0" != "$?" ]] && die "COVID-19 repository failed to update" 16
-    popd
-
-    timeStamp=$(TZ=":Etc/UTC" date +"%Y-%m-%dT%H:%M:%SZ")
-    printf "\nCompleted on %s\n" "$timeStamp" >> "$UPDATE_NOTICE"
-} # updateCOVID19DataSources
-
-
-function generateVirusUpdateJSONFiles {
-    echo "vujson - generating virus update JSON files"
-
-    env | awk '/VIRT/' | sort
-    python3 -m covidvu.pipeline.vujson confirmed deaths
-    [[ "0" != "$?" ]] && die "generateVirusUpdateJSONFiles - failed" 17
-    ls -Alrt "$SITE_DATA_DIR" | awk '!/conf-int/ && !/mean-/'
-} # generateVirusUpdateJSONFiles
-
-
 function generateHospitalBedsJSONFiles {
     local hospitalBedsTargetFile="$SITE_DATA_DIR/hospital-beds-count-US.json"
 
@@ -145,16 +115,16 @@ function generateCountiesUSJSONFile {
 } # generateCountiesUSJSONFile
 
 
-function fetchBNODataSource {
+function fetchJITDataSource {
     echo "+++++"
     curl -A "$PYAVKA_USER_AGENT" -vi -o "$RAW_DATA_FILE" --connect-timeout 20 "$RAW_DATA_SOURCE" | 
-    [[ "0" != "$?" ]] && die "fetchBNODataSource unable to fetch $RAW_DATA_SOURCE" 20
+    [[ "0" != "$?" ]] && die "fetchJITDataSource unable to fetch $RAW_DATA_SOURCE" 20
 
     cat "$RAW_DATA_FILE" | awk '/<table/ { gsub("<table", "\n<table"); gsub("/table>", "/table>\n"); print; }' | \
     awk -v "H=$HTML_FILE_NAME" '/<table/ { o = sprintf(H, n++); print > o; close(o); }'
-    [[ "0" != "$?" ]] && die "fetchBNODataSource invalid $RAW_DATA_FILE HTML scraping issue" 21
+    [[ "0" != "$?" ]] && die "fetchJITDataSource invalid $RAW_DATA_FILE HTML scraping issue" 21
     echo "+++++"
-} # fetchBNODataSource
+} # fetchJITDataSource
 
 
 function patchJSONFiles {
@@ -170,7 +140,7 @@ function patchJSONFiles {
     then
         now=$(date)
         echo "pyavka - grabbing the spreadsheet"
-        fetchBNODataSource
+        fetchJITDataSource
         python3 -m covidvu.pipeline.pyavka
         ls -Alrt "$SITE_DATA_DIR"/*html
 
@@ -239,9 +209,6 @@ echo "*** COVIDvu - website refresh tool ***"
 assertSiteDataExists
 resetErrorNotification
 resetSiteData "$1"
-assertCOVID19DirExists
-updateCOVID19DataSources
-generateVirusUpdateJSONFiles
 generateHospitalBedsJSONFiles
 generateCountiesUSJSONFile
 patchJSONFiles "$2"
